name: .NET Framework Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: choco install netfx-4.7.2-devpack -y

    - name: Install Visual Studio Build Tools
      run: choco install visualstudio2019buildtools -y

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -p:Platform="Any CPU"

    - name: Test
      run: dotnet test --no-build --verbosity normal
